---
title: 'Ranchi District : Finance Commision Dashboard'
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Row {data-height=400}
-----------------------------------------------------------------------

### Expenditure by Ranchi District for 14th Finance Commission

```{r fig.width=20}

library(readxl)
library(gridExtra)
options(scipen=999)     # for omitting exponential values in graph
ranchi<-read_excel("ranchi_data.xlsx")
#class(ranchi)
category=c('Received','Spent','Received','Spent','Received',
           'Spent','Received','Spent')
year=c("2015-16","2015-16","2016-17","2016-17","2017-18"
       ,"2017-18","2018-19","2018-19")
Amount=c(as.integer(ranchi[327,4])/10000000,as.integer(ranchi[327,11])/10000000
         ,as.integer(ranchi[327,5])/10000000,as.integer(ranchi[327,12])/10000000,
         as.integer(ranchi[327,6])/10000000+as.integer(ranchi[327,7])/10000000,
         as.integer(ranchi[327,13])/10000000,as.integer(ranchi[327,9])/10000000,
         as.integer(ranchi[327,14])/10000000)
Finance=data.frame(category,year,Amount)
library(ggplot2)
ggplot(Finance, aes((year), Amount, fill = category)) + 
  geom_bar(stat="identity", position = "dodge") + 
  scale_fill_brewer(palette = "Set1") + ggtitle("Amount Received and Spent on yearly basis from 2015-19 by Ranchi district") + labs(y="Amount (in Crores)") ->p1



block<-read_excel("blocks.xlsx")
ranchi<-read_excel("ranchi_data.xlsx")
na_vec=which(!complete.cases(ranchi))
ranchi_clean=ranchi[na_vec,]
x=unique(ranchi_clean$Block)
x=x[!x %in% x[6]]
x=x[3:20]
b=c(x,x)
b_rs=c(as.numeric(unlist(c(block[10])))/10000000,
       as.numeric(unlist(c(block[15])))/10000000)
category=c(rep('Received',18),rep("Spent",18))

b_data=data.frame(category,b,b_rs)

ggplot(b_data, aes(b, b_rs , fill = category)) + 
  geom_bar(stat="identity", position = "dodge") + 
  scale_fill_brewer(palette = "Set1") + labs(y="Amount (in Crores)",
                                             x="") +
  theme(axis.text.x=element_text(angle=90, hjust=1)) +
  ggtitle("Amount received and spent by each block of Ranchi district from 2015-19")  -> p2


grid.arrange(p1, p2, ncol = 2)

```

Row { .tabset .tabset-fade}
-----------------------------------------------------------------------

### Yearwise Expenditure by Blocks

```{r}
column( 3,
selectInput("Block1", label = "Select Block",
            choices = x),
selectInput("Year", label = "Select year",
            choices = c("2015-16","2016-17","2017-18","2018-19"), selected = "2015-16")
)
#abc="BURMU"
column( 7,
renderPlot(
{
ab=input$Block1
block=read_excel(eval(paste0(ab,".xlsx")))
pnchyt=c((block[3]))
if(input$Year=="2015-16")
{
spent=as.numeric(unlist(c(block[11])))/100000
receive=as.numeric(unlist(c(block[4])))/100000
}
else if(input$Year=="2016-17")
{
spent=as.numeric(unlist(c(block[12])))/100000
receive=as.numeric(unlist(c(block[5])))/100000
}
else if(input$Year=="2017-18")
{
spent=as.numeric(unlist(c(block[13])))/100000
receive=(as.numeric(unlist(c(block[7])))+as.numeric(unlist(c(block[6]))))/100000
}
else
{
spent=as.numeric(unlist(c(block[14])))/100000
receive=as.numeric(unlist(c(block[9])))/100000
}

b_p=data.frame(pnchyt,round(receive,digits = 2)
               ,round(spent,digits = 2))
names(b_p)=c('pnchayat','receive','spent')
cols=c("orange","green")
barplot(
  t(b_p[c('receive','spent')]),
  beside=T,
  ylim = c(0,20+max(c(receive,spent))),
  col=cols,
  main =paste('Analysis of year',input$Year), 
  names.arg=b_p$pnchayat,
  las=2, cex.names = 0.8,# xaxt='n',
  ylab='Amount (in Lakhs)',
  legend.text=c('Received','Spent')
)
box()
}
)
)
```

### Panchayatwise Expenditure by Blocks

```{r}
column( 4,
selectInput("Block2", label = "Select Block",
            choices = x)
)
#print({input$Block})
column( 6,
renderPlot(
{
abc=input$Block2
block=read_excel(eval(paste0(abc,".xlsx")))
pnchyt=c((block[3]))
#kable(pnchyt[,1:2],caption="Panchayats in Khelari Block" )
spent=as.numeric(unlist(c(block[15])))/100000
receive=as.numeric(unlist(c(block[10])))/100000
b_p=data.frame(pnchyt,round(receive,digits = 2)
               ,round(spent,digits = 2))
names(b_p)=c('pnchayat','receive','spent')
cols=c("red","blue")
barplot(
  t(b_p[c('receive','spent')]),
  beside=T,
  ylim = c(0,20+max(c(receive,spent))),
  col=cols,
  main =paste('Distribution of funds in',abc, 'Block (2015-19)'),cex.main=1, 
  names.arg=b_p$pnchayat,
  las=2, cex.names = 0.8,# xaxt='n',
  ylab='Amount (in Lakhs)',
  legend.text=c('Received','Spent')
)
box()
}))

```

